<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\TrainingCategory\TrainingCategoryEntry.razor" />
    <Content Remove="wwwroot\files\abc.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\files\abc.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\bootstrap\" />
    <Folder Include="wwwroot\image\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\files\FormTest\2d3c7a8f-435c-4542-97f0-bedc72da02f2_rffile_city.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>



</Project>
